site:
  title: My first antora demo site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://pages.github.com/DanielH18/static-page/
  start_page: component-b::index.adoc
content:
  sources:
    - url: https://github.com/DanielH18/static-page-component-a.git
      branches: main
      # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
      # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
      edit_url: false
    - url: https://github.com/DanielH18/static-page-component-b.git
      branches: [main]
      start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
