name: Antora Test Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SITE_DIR: 'site'

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: antora-playbook.yml
      - name: "List folder"
        run: |
          ls -ltr $GITHUB_WORKSPACE/build/site
      - name: "Upload generated site"
        uses: actions/upload-artifact@v4.3.1
        with:
          name: site
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download generated site
        uses: actions/download-artifact@v4.1.7
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: "${{ env.SITE_DIR }}"
